DeNA/HandyRL

connection.py
train.py
worker.py

Removed 'SafeThread' and 'SafeProcess' class and ensure shutdown by 'Ctrl + C' by 'try ~ finally' structure.

Finish threads by wrapping by 'try: finally:'

---

connection.py

Remove
boolean debug
and
function debug_print()
in connection.py since they are not used.

Remove unused debug function

---

evaluation.py

Remove non-english characters, the add comment

Remove non-ascii suffix that express first or second player

---

config.yaml
environment.py
environments/geister.py
environments/tictactoe.py
evaluation.py
generation.py
model.py
train.py
util.py
worker.py

- multi role worker mode
- accept any format of input
- dict style player notation

Update new version

---

environment.py
environments/geister.py
environments/tictactoe.py
evaluation.py
generation.py
model.py
train.py
worker.py

- Change inner functions to global functions (for Python3.8)
- Fix learning late decay
- Fix default player name in evaluation.py
- Use yaml.safe_load function since yaml.load() function without additional arguments is deprecated

Fix for Python3.8 and small updates

---

train.py

Rewrote callback functions for batcher as member functon for using process-based Batcher in Python 3.8.

update: callback functions in Batcher as member function

---

config.yaml
generation.py
train.py

Thread-style batcher is currently useless.
Therefore, changed to using batcher process in default setting. (Added in config.yaml.)

Update: use batcher process in default setting

---

environments/geister.py
train.py

There should be a bug in the code of inference mask generation in train.py.
In addition, duplicate count feature in geister.py seems to be a bug.

Bugfix: training recurrent networks

---

generation.py
train.py

In current implementation of episode buffer,
training with very long episodes costs much time for decompressing episodes.
In this PR, episode is compressed step by step which enables us to use this library for long, real-like situations.

Compress and decompress step by step

---

environment.py
evaluation.py
generation.py

Minor updates

---

train.py

Move cuda() operation from receiver thread to train function.

fix: load batch on GPU in trainer's main thread

---

config.yaml
train.py

restart_epoch:  100  <- then we can restart training from models/100.pth

feature: add restart_epoch in config.yaml

---

config.yaml
train.py

We can set lambda in config.yaml

update: lambda in config.yaml

---

environments/geister.py

conv style policy for fast training

feature: update network style of Geister

---

evaluation.py
train.py

loading partial model (official implementation version)

update: load model with strict=False

---

config.yaml
generation.py
train.py

separate every 'compress_steps' moment and compress each block

feature: compress steps in config.yaml

---

train.py

Important bugfix.
Training RNNs was not enabled so far. :(

fix: forword computation of RNN in training

---

evaluation.py

agent.action(player)
for parallel action, playerwise action index

Add player argument to Agent class in evaluation.py

---

train.py

from
data, data, data, ... -> batch
to
[data, data, ...] -> batch

feature: send batch data to batcher (not per episode)

---

environment.py
environments/geister.py
environments/tictactoe.py
evaluation.py

For counterform games (Geister, Chess, Shogi...), network input from different perspective and symmetric action index help training.
Since it requires another argument for action2str and str2action, we should merge parallel_action branch before merging this one.

action index different for each player, especially for symmetric environment

---

handyrl/evaluation.py
handyrl/train.py

feature: save latest model

---

handyrl/environments/geister.py
handyrl/environments/tictactoe.py
handyrl/generation.py
handyrl/model.py
handyrl/train.py
handyrl/util.py

few changes by PEP8
How about , at the end of lists?

chore: fix styles

---

handyrl/train.py

feature: output epoch number to console

---

handyrl/evaluation.py
handyrl/train.py
handyrl/worker.py

return {'args': args, 'result': result}
from Evaluator and then process in Learner
We need more discussion about the communication style.

feature: dict style evaluation result and gather data in Learner

---

config.yaml
handyrl/train.py

entropy regularization_decay:
constant regularization -> 1.0
decay according to game progress -> smaller value

feature: entropy_regularization_decay in config.yaml

---

handyrl/train.py

feature: generation stats + record evaluation results as mean, std

---

handyrl/evaluation.py
handyrl/model.py
handyrl/train.py

import SimpleConv2DModel as DefaultModel

chore: rename DuelingNet as SimpleConv2DModel

---

handyrl/environment.py

calling chance() function is worth nothing

fix: default chance_info function should do nothing

---

handyrl/train.py

fix: set value_targets and value_advantages when not using value

---

handyrl/train.py

also considering another idea (not using player index)

fix: player index with env.players() in feed_episodes()

---

handyrl/environment.py
handyrl/environments/geister.py
handyrl/environments/tictactoe.py
handyrl/evaluation.py

We need player argument in diff_info() function to choose information to be sent in imperfect information games.

feature: player argument for diff_info() function

---

handyrl/environment.py
handyrl/environments/geister.py
handyrl/environments/tictactoe.py
handyrl/evaluation.py

info = {'move': 'B3B4', 'captured': 'R'}

feature: geister diff info piece color

---

handyrl/evaluation.py

now we can set temperature of agents

feature: rewrite agent class and add ensemble agent class

---

config.yaml
handyrl/connection.py
handyrl/train.py

Remove use_batcher_process configuration

---

handyrl/evaluation.py

small but fatal bug when using observation=True

fix: use plan() function in Agent.observation()

---

handyrl/evaluation.py
handyrl/generation.py

feature: avoid importing model.py from generation.py and evaluation.py

---

config.yaml
handyrl/losses.py
handyrl/train.py

Add handyrl/losses.py
select policy target algorithm and value (& return) one separately

(WIP) feature: policy, value (& return) target selection

---

handyrl/environments/geister.py
handyrl/evaluation.py
handyrl/generation.py
handyrl/model.py
handyrl/train.py

It would be good update for custom output but some of new implementation are too abstract.

(Idea) dict style NN outputs and training pipeline

---

handyrl/train.py

it's not necessary but imbalanced.

feature: no vmask summarization in two-player games

---

handyrl/generation.py
handyrl/train.py

new PR
pmask -> action_mask
tmask -> turn_mask
vmask -> observation_mask

feature: mask name easy to understand

---

handyrl/generation.py

careless bug. We need to test for such case...

fix: hidden update in generator

---

handyrl/generation.py
handyrl/model.py
handyrl/train.py

current -> ... -> (this PR) -> ... -> parallel action 
B x T x P x ...

feature: 4-D style batch for parallel action

---

handyrl/model.py

It's more general way. It will help users who want to use BoolTensor or other data types.

feature: use torch.from_numpy()

---

handyrl/environments/geister.py
handyrl/environments/tictactoe.py
handyrl/evaluation.py
handyrl/generation.py
handyrl/model.py
handyrl/train.py
handyrl/util.py

Small updates will be gathered to this PR.

chore: Small Updates 2021/01 

---

handyrl/train.py

fix: episode mask 

---

LICENSE

The format was broken, so I fixed the format.

Format a LICENSE

---

README.md

add comments for multiple workers, fix hungry_geese.py path

chore: note multiple workers, fix wrong path

---

handyrl/envs/kaggle/hungry_geese.py

fix: main function of hungry_geese.py

---

handyrl/evaluation.py

feature: set default_agent to random agent

---

config.yaml

e.g.
min 400
update 200
max 100000

feature: set min/max/update games smaller numbers

---

main.py

feature: set OMP_NUM_THREADS=1 in main.py

---

README.md

I think this error will be frequently asked question.

feature: how to solve too many files error

---

README.md

fix: small change in README.md

---

handyrl/envs/kaggle/hungry_geese.py

We need to accept last_actions in reset_info() if diff_info() send it.

fix: network interface of hungry geese environment

---

handyrl/evaluation.py
handyrl/generation.py
handyrl/util.py

Since softmax function will be widely used, implementing common function might be useful.

feature: softmax in util.py

---

.gitignore

simple one, or widely used template ?

feature: add gitignore

---

handyrl/model.py

Small updates will be gathered here.

chore: Small Updates 2021/02

---

docs/custom_environment.md
handyrl/envs/kaggle/hungry_geese.py
handyrl/evaluation.py

fix: using step() and step_info()

---

handyrl/environment.py
handyrl/envs/geister.py
handyrl/envs/kaggle/hungry_geese.py
handyrl/envs/tictactoe.py
handyrl/evaluation.py

reset_info(), step_info() -> update()

(Idea) update() method in environments

---

docs/custom_environment.md
handyrl/environment.py
handyrl/envs/geister.py
handyrl/envs/kaggle/hungry_geese.py
handyrl/envs/parallel_tictactoe.py
handyrl/envs/tictactoe.py
handyrl/evaluation.py
handyrl/generation.py
tests/test_environment.py

feature: use play() method and step() method

---

handyrl/envs/geister.py
handyrl/envs/tictactoe.py

This is already no meaning.
Would we need load() function instead ...?

chore: remove play() with record string

---

main.py

to cleanly finish stand-alone training

fix: if or elif in main.py

---

handyrl/envs/kaggle/hungry_geese.py
handyrl/evaluation.py

We might need environment test with update() interface.

fix: step info to update, bug in Hungry Geese

---

.github/workflows/action.yaml
tests/test_environment.py

I had not added Hungry Geese to test_environment.py.
That's why bug in HG env had not been found.

fix: add Hungry Geese to environment test

---

handyrl/envs/geister.py
handyrl/envs/parallel_tictactoe.py
handyrl/envs/tictactoe.py
tests/test_environment.py

environment test with network battle interface

feature: add network battle interface test

---

handyrl/envs/parallel_tictactoe.py

small changes will be gathered into this PR.

chore: Small Updates 2021/03

---

tests/test_environment.py

feature: test server client equality

---

handyrl/envs/geister.py

unknown opponent piece *
1 2 3 4 5 6
A _ _ B _ R _
B _ _ _ _ _ R
C R * _ _ _ _
D _ _ _ _ _ _
E _ _ * * _ _
F _ * _ _ _ _
color = B

feature: output unknown piece char

---

handyrl/evaluation.py
handyrl/model.py
handyrl/train.py

Since official Conv2d net is nn.Conv2d, this is more consistent.

feature: change SimpleConv2DModel -> SimpleConv2dModel

---

handyrl/envs/geister.py

before
0 ~ 143 move action
144 ~ 213 set action of first player
214 ~ 284 set action of second player
after
0 ~ 143 move action
144 ~ 213 set action

feature: common set action index in Geister

---

config.yaml
handyrl/environment.py

feature: specify environment by env name

---

handyrl/agent.py
handyrl/evaluation.py

This division will help us easily implementing when we write special agent class.

(Idea) feature: divide evaluation.py into agent and eval

---

.github/workflows/action.yaml

new version of #164
Several versions of Python are also tested.

feature: add test on Windows and MacOSX (simpler way)

---

handyrl/envs/geister.py
handyrl/envs/kaggle/hungry_geese.py
handyrl/envs/tictactoe.py
handyrl/evaluation.py
handyrl/model.py
handyrl/train.py
handyrl/worker.py

We can define and use naive PyTorch Model by this update, while we have to decide all configuration of defined models.

(Idea) feature: base model class -> model wrapper class

---

handyrl/__init__.py
handyrl/train.py

learner = Learner(env=Environment, net=Net, args=args)
learner.run()

feature: import based enabled

---

handyrl/evaluation.py

reset() was not called in evaluation client

fix: call reset() in evaluation client

---

config.yaml
handyrl/train.py

We can set `epochs`.
If `epochs` < 0, there is not limit.

feature: maximum epochs

---

handyrl/__init__.py

from handyrl.train import Learner
or 
Making new wrapper class in new __init__.py

feature: remove __init__.py

---

handyrl/train.py
requirements.txt

- set memory fraction ratio
- output warning and prevent increasing buffer size
Does this implementation cost much?

(WIP) feature: memory usage warning and buffer elimination

---

handyrl/agent.py
handyrl/evaluation.py

I move view() function into evaluation loop and NetworkAgentClient
In current code, we cannot watch games within random or rule-based agents.
These interfaces should be organized again.

feature: view function in evaluation loop

---

handyrl/connection.py

Massively thanks to **zuijiang** in Kaggle forum!!
https://www.kaggle.com/c/hungry-geese/discussion/218190

fix: add connection

---

handyrl/envs/kaggle/hungry_geese.py
handyrl/train.py
handyrl/worker.py

Small changes will be gathered into this PR.

chore: 2021/04

---

handyrl/worker.py

server side
```
from handyrl.train import Learner
from handyrl.envs.tictactoe import Environment
from handyrl.envs.tictactoe import SimpleConv2dModel as Net
if __name__ == '__main__':
with open('../config.yaml') as f:
args = yaml.safe_load(f)
print(args)
learner = Learner(env=Environment, net=Net, args=args, remote=True)
learner.run()
```
worker side
```
from handyrl.worker import RemoteWorkerCluster
if __name__ == '__main__':
with open('../config.yaml') as f:
args = yaml.safe_load(f)
print(args)
worker = RemoteWorkerCluster(args=args['worker_args'])
worker.run()
```

feature: import based worker

---

handyrl/model.py
main.py

(Idea) feature: OMP_NUM_THREADS=1 in model.py

---

config.yaml
handyrl/evaluation.py

```
eval:
opponent: ['random', 'rulebase']
```

(Idea) feature: set evaluation agent

---

handyrl/train.py
handyrl/worker.py

WorkerCluster ... for local workers
WorkerServer ... for remote workers
entry server is moved into WorkerServer from Learner

feature: divide WorkerCluster into WorkerCluster and WorkerServer

---

handyrl/evaluation.py

selected `opponent` was not used

fix: use selected opponent

---

handyrl/train.py

This one is not heavy, but not strict.

(Idea) fix: lazy memory limit

---

handyrl/train.py

Is simply using `epoch` better?

chore: model_era -> model_epoch

---

handyrl/train.py
handyrl/worker.py

How about creating random models on the worker's side?

feature: create random model at worker

---

docs/custom_environment.md
handyrl/environment.py
handyrl/envs/geister.py
handyrl/envs/kaggle/hungry_geese.py
handyrl/envs/tictactoe.py
handyrl/model.py
handyrl/train.py
handyrl/worker.py
tests/test_environment.py

feature: no action length

---

handyrl/model.py
handyrl/train.py
handyrl/worker.py

We don't need action_length() if we can create RandomModel with trainable model and inputs.
However, there is a problem when it is difficult to call observation() on the server side, such as in the google football environment.

(Idea) feature: create random model with trainable model and inputs

---

handyrl/train.py

```
a, b, c, d = [to_torch(np.array(val)) for val in zip(*datum)]
```
will make it easier to add new tensors in batch creation.

chore: simple batch zip

---

handyrl/evaluation.py

fix: get model func model instance

---

handyrl/losses.py

Should we leave any warnings when the MC is forced to be used?

feature: use Monte Carlo loss if no baseline

---

README.md

The use cases should be updated!
I think that the 1st `place` solution would be kind.

feature: link the 1st place solution in Hungry Geese competition

---

handyrl/envs/geister.py

feature: explain DRC net

---

handyrl/agent.py

This check is tedious, but it's gentler.

fix: there is cases if we have no value outputs nor policy outputs

---

handyrl/envs/geister.py
handyrl/train.py
handyrl/worker.py

Small changes will be gathered here.

chore 2022/01

---

handyrl/environment.py

chore: update description of observers()

---

handyrl/envs/kaggle/hungry_geese.py
handyrl/envs/tictactoe.py
handyrl/model.py

Another version of #218
= 1 or more

feature: hidden hidden argument count

---

handyrl/generation.py
handyrl/train.py

I realized that the behavioral policies are used only for the chosen actions.
This change can save a lot of buffer memory when the action space is large.
Is there an algorithm that uses behavioral policies for unselected actions?

(To be discussed) feature: store selected probability only (IMPORTANT)

---

handyrl/envs/kaggle/hungry_geese.py
handyrl/envs/tictactoe.py
handyrl/model.py

Revert "feature: hidden hidden argument count"

---

scripts/make_onnx_model.py

1.pth.onnx -> 1.onnx
It's simpler and unconfusing.

feature: save_model.pth.onnx -> saved_model.onnx

---

handyrl/model.py
handyrl/train.py
scripts/make_onnx_model.py

Small changes for the next release.

chore 2021/01 2nd

---

handyrl/train.py

This is problematic when tranining a strategy with two players acting simultaneously.

fix: consider the case when training policies of two players

---

handyrl/train.py

As same as #264, we should not assume that turn player is only one.

fix: no computing turn_advantages

---

handyrl/train.py

I think this is more polite and safer, but we have to be careful because the behavior changes.

(Behavior Change) feature: count, output and use num of returned episodes

---

handyrl/train.py

feature: use length=1 queue for easier model update

---

config.yaml
handyrl/environment.py
handyrl/evaluation.py
handyrl/generation.py

Reverts DeNA/HandyRL#265
This PR is returned to discussion.

Revert "feature: remove observers() and add observatin config in env_args"

---

handyrl/evaluation.py

Is there any other ERROR cases?

fix: catch ConnectionResetError in eval_client mode

---

handyrl/evaluation.py

fix: catch ConnectionResetError in network client agent

---

handyrl/train.py

Small changes will be gathered here.

chore 2022/02-2

---

handyrl/agent.py

fix: ensemble agent

---

handyrl/evaluation.py

Since inference() accepts batches, init_hidden() should do the same.

fix: enable to input batch_size to OnnxModel.init_hidden()

---

handyrl/evaluation.py

Using like build_agent('rulebase') is simple.

feature: set default value to env argment in build_agent()

---

handyrl/worker.py

Small updates will be gathered here.

(chore) 2022/03

---

handyrl/agent.py

Small changes will be gathered here.

chore: 2022/03 v2

---

handyrl/connection.py
handyrl/train.py
handyrl/worker.py

Can this implementation easily finish every process?

(Idea) feature: daemonic threads & daemonic batcher processes & wait stopping workers

---

handyrl/connection.py
handyrl/train.py
handyrl/worker.py

This is just an idea, but it's very simple.

(Idea) experiment: set all threads daemon=True and remove shutdown flags

---

handyrl/evaluation.py

We can easily use onnx models.

feature: set model=None in load_model()

---

handyrl/agent.py
handyrl/envs/kaggle/hungry_geese.py
handyrl/evaluation.py

Switch rulebase agents, such as `rulebase-greedy` or `rulebase-do_nothing`.

feature: rulebase agents with keys

---

handyrl/agent.py

fix: set key for rule-based agents

---

handyrl/evaluation.py

```
python3 main.py -e models/latest.pth:rulebase 1 1
```

feature: opponent selection by :

---

handyrl/train.py

Ensure that the accept_rate is not negative.

feature: divide ep count variable

---

handyrl/envs/geister.py

- board view
- better neural net?
- preparation for piece color estimation>

(WIP) update Geister sample 

---

handyrl/train.py

I would like to avoid strange behavior in the target-value-averaging setting in situations as when generating matches that are not self-playing with a certain probability.

feature: apply omask for two-player value averaging for solo-play

---

handyrl/train.py

We no longer need to change two parts of code when changing the elements of a batch.

feature: data gathering code both for solo/multi player training

---

.github/workflows/action.yaml

feature: add python3.10 test
