connection.py
train.py
worker.py

Opening threads with `daemon=True` is not necessary.

Remove daemon flags of threads

---

model.py

Resolve `TypeError: tuple() takes at most 1 argument (2 given)`.
`python train.py` is passed with the environments, TicTacToe and Geister.

Change tuple with list in ConvLSTMCell.init_hidden()

---

environments/tictactoe.py
train.py

Fix the bug that train.py raises an error when env.player() returns the player list of string like ['Player1', 'Player2'].

FIX: get player indices of model_id from env.players()

---

handyrl/train.py

fix: set current model as 'model' first when loading old model

---

handyrl/environment.py

Calling overridden reset() function before setting each environment is clearly bad procedure.

fix: stop calling reset() in the construtor of BaseEnvironment

---

main.py

`importing required libraries only` is a good feature for extensibility.
e.g. importing torch is useless for evaluating rule-based agent against random agent

feature: importing only required endpoint function in main.py

---

config.yaml

With value 0.3, training of TicTacToe on local machine looks too slow.

(Idea) change entropy regularization coefficient from 0.3 -> 0.1

---

handyrl/environments/geister.py

Each player can set first piece positions in the original geister game.
But there is a problem;
original positions will be deterministically chosen by Agent.action().
Therefore, evaluating models with zero temperature may be unsuitable.

(Idea) feature: set original state as action in Geister

---

handyrl/connection.py
handyrl/worker.py

multiprocessing.connection.Pipe() -> multiprocessing.Pipe()
https://docs.python.org/3/library/multiprocessing.html#multiprocessing.Pipe

fix: calling multiprocessing.Pipe

---

handyrl/model.py

We should be more careful after using from_numpy().

fix: random model outputs p, v with dtype=np.float32

---

handyrl/evaluation.py

strict=False often causes a big mistake.

feature: strict=True in evaluation mode

---

handyrl/connection.py

It seems a bug but it rarely caused an error in small scale experiments.

fix: handle ConnectionResetError when sending data

---

handyrl/train.py
handyrl/worker.py

Pickle PyTorch model before sending data

Fix: `unable to open shared memory object` error in multiprocessing

---

handyrl/connection.py

for Windows OS
However, on MacOSX the following error was occured:
```
AttributeError: module 'multiprocessing' has no attribute 'connection'
```
on worker mode, while importing torch in connection.py avoided it ... why?

fix: replace select.select() to multiprocessing.connection.wait()

---

handyrl/train.py

Since the number of Batchers should be large enough, buffer_size=1 is usually OK.

feature: change buffer_size of Batcher from 3 to 1

---

handyrl/train.py

Currently, `env` argument of Learner is not working.

fix: remove env argument from learner

---

handyrl/agent.py

Such substitution sometimes causes terrible situations when we develop something based on HandyRL.

chore: remove unsafe -=

---

handyrl/agent.py

This is necessary to use critic in evaluation move.
However, we are considering about remaining observe() interface itself or not.

fix: return value 1-d tensor in observe() function

---

handyrl/util.py

```
def softmax(x):
x = np.exp(x - np.max(x, axis=-1, keepdims=True))
return x / x.sum(axis=-1, keepdims=True)
```
keepdims=True is better when handling multi-dimensional inputs

chore: small fix of keepdims in softmax() function

---

handyrl/train.py

It is wrong to make an observation mask based on the presence or absence of value output when you can train a model with no baseline output.

feature: (idea) create observation mask from observation!=None

---

handyrl/envs/geister.py

I used this PyTorch LSTM implementation as a reference.
https://pytorch.org/docs/1.9.1/generated/torch.nn.LSTM.html
And, I'd like to thank @ikki407 for finding this bug!

feature: true drc

---

handyrl/evaluation.py

`load_model()` is more natural than `get_model()`.
Especially for ONNX models, the model can be loaded with just the `model_path`.
Therefore, it makes more sense to have the `model_path` as the first argument, as in build_agent(), but I'm not sure.

feature: use load_model() function

---

handyrl/train.py

This is just a bug, and we don't need any Batcher if self.optimizer is `None`.

fix: trainer for non trainable model

---

handyrl/envs/geister.py
handyrl/model.py

Currently, users have to define `init_hidden()` method like this:
```
def init_hidden(self, batch_size)
if batch_size is None:
return numpy-array
else:
return torch-tensor
```
, while this writing rule has little advantage except small speedup.

(Idea) feature: init hidden torch

---

handyrl/agent.py
handyrl/environment.py
handyrl/evaluation.py
handyrl/generation.py

Each environment should determine the observers at each turn.
Next problem: How do you use the observation argument, and is it necessary?

(WIP) feature: add observers() method in environments

---

handyrl/evaluation.py

ONNX models are very useful for both competitions and business projects.

(WIP) feature: ONNX support for evaluation

---

handyrl/envs/kaggle/hungry_geese.py
handyrl/envs/tictactoe.py
handyrl/model.py

It's strange to require hidden as an argument even when it's not an RNN.
However, it is now necessary to input the hidden state as "hidden".

(Idea) feature: unnecessary hidden argument

---

scripts/make_onnx_model.py

#233 enables us to use ONNX model created by this script.

feature: add make_onnx_model.py

---

handyrl/worker.py

Worker IDs should be cumulative, or the initial states may be covered.
I think I had implemented this feature before...?

feature: assign cumulative worker index

---

scripts/aux_swa.py

Should we change the script name?

feature: add scripts/aux_swa.py

---

handyrl/evaluation.py

I don't think it's an important point, though.

chore: since critic is not necessary, it should be None at default

---

handyrl/train.py

(Immediately) fix: cut batch and output along time-axis

---

scripts/requirements.txt

I think users enable to know which libraries will be needed after running scripts, but requirements.txt will them.
While `onnxruntime` is actually not necessary for `make_onnx_model.py`, it will help understanding about the usage of the generated ONNX models.

feature: add requirements.txt for scripts/

---

handyrl/train.py

It may be easier to write them separately like this.
However, the behavior of "whether or not to stop training when the number of matches in the buffer decreases later" will change.

feature: divided wait, start, run in training

---

handyrl/connection.py

I'd like to remember why we needed conn_index.
If there are more connections, would set() be better?

(Idea) chore: use simple list for QueueCommunicator.conns

---

handyrl/train.py

After #273, we don't have to consider update() call before starting training, do we?

feature: remove before starting training check

---

handyrl/model.py

Since the shape of hidden outputs is free, we should not apply `np.zeros_like` with hidden outputs.
```
map_r(outputs, lambda o: np.zeros_like(o) if o is not None else None)
```
is more general but currently it might be too abstract.

fix: remove hidden output from random model

---

.gitignore

We already officially supported saving and loading ONNX models.

feature: add *.onnx to .gitignore

---

scripts/make_onnx_model.py

I didn't know `rstrip`'s behavior...
```
a = 'models/latest.pth'
a.rstrip('.pth') + .onnx #-> 'models/lates.onnx'
```
```
import re
re.sub('\.pth$', '.onnx', a)  #-> 'models/latest.onnx'
```

fix: onnx saved model name

---

handyrl/worker.py
main.py

This is useful when you want to quickly change just the number of workers, such as when the two machines sharing a disk have different numbers of CPUs, or when you also want to reserve a few workers aside from the training machine.

(Idea) feature: fast worker count config

---

handyrl/connection.py

`set.discard(a)` doesn't raise unfound error.

feature: use set instead of list for connections in QueueCommunicator

---

handyrl/worker.py

It is unnatural that the buffer length of the buffering mechanism for Gathers is divided between args and episodes, etc.

feature: use same buffer_length for buffering system in Gather

---

handyrl/connection.py
handyrl/train.py
handyrl/worker.py

After #307 , we can add `connection_count()` interface to prevent direct access to `conns`.

feature: connection count interface

---

handyrl/evaluation.py

fix: stop calling view_transition() in reset phase

---

handyrl/model.py

When we call `inference()` with some keyword arguments, RandomModel should accept them.

chore: add kwargs to random model

---

handyrl/train.py

So far, the adoption rate in the replay buffer has been linear based on `maximum_episodes`, but this means that the earliest episodes will be selected many times before the buffer is filled.
Even if the diversity in each batch will be decreased a little, it would be better to use a weight proportional to the number of current episodes so that the earliest episodes are less likely to be selected.

(Idea) feature: proportional accept rate during all phases

---

handyrl/train.py

There was a possibility of stopping with an error when the buffer became short due to insufficient memory.

fix: episode selection index error

---

scripts/win_rate_plot.py

fix: prevent array length error in win_rate_plot.py

---

handyrl/train.py

```
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
```
After the training started in the 0th generation, when the worker was reconnected, the above error occurred because Learner's self.model was on the GPU.

fix: remove map_location=cpu error after starting training

---

handyrl/connection.py

I have never concerned `fineno()` interface. Is it useful?

chore: remove fileno() inferface from PickledConnection

---

.github/workflows/action.yaml
tests/test_environment.py

Is checking kaggle-environments in github tests necessary?

feature: remove installation of kaggle environments from github actions

---

handyrl/connection.py

This reverts commit 31b8fb9b486ee6db93bef125da8197fcb1e328d1.

Revert "chore: remove fileno() inferface from PickledConnection"

---

handyrl/train.py

```
v = outputs.get('value', None)
moment['value'][player] = v
```
Since `v` is a scalar but one-dimensional value, the padding should be [0].

fix: value padding with [0]

---

handyrl/worker.py

We can easily change the number of pooled models in each worker.
(TODO: Can we prioritize which model to save?)

feature: model pool in each worker
